### ISSUE TITLE
When is url rewrite imported when product is imported?

### ISSUE THREAD

**Issue by adhocore** [techdivision/import-product-url-rewrite#21]
According to [docs](https://docs.m2if.com/38/file-structure/product-import-urls):
```
By default, the product URL rewrites will be imported with the full product import,
read the appropriate documentation section therefore.
```

I have product import with sku, categories, visibility, store view code, product websites, name (which gives url key) but it doesnot import url rewrite, only imports product with url key.

**Comment by wagnert** [comment]
This may depend on different circumstances. Can you please provide a little bit more context for the issue

* M2IF version you are using
* PHP version you are using
* Configuration file/snippets (depending on the M2IF version you are using)
* Example files we can use to reproduce the issue

Additionally it'll be very helpful, if you can add instructions that make the reproduction of the issue a bit easier for us.

Thanks for reporting!

**Comment by adhocore** [comment]
i think it is due to my custom config and file naming. will try to figure out.

closing now, i will reopen if needed.

**Comment by wagnert** [comment]
Thanks @adhocore
